if(NOT DEFINED FIXTURE_DIR)
    message(FATAL_ERROR "FIXTURE_DIR is required")
endif()

file(STRINGS "${FIXTURE_DIR}/SHA256SUMS" checksum_lines)
foreach(checksum_line IN LISTS checksum_lines)
    string(REGEX MATCH "^([0-9a-f]+)  (.+)$" matched "${checksum_line}")
    string(LENGTH "${CMAKE_MATCH_1}" expected_hash_length)
    if(NOT matched OR NOT expected_hash_length EQUAL 64)
        message(FATAL_ERROR "Invalid audio fixture checksum row: ${checksum_line}")
    endif()
    set(expected_hash "${CMAKE_MATCH_1}")
    set(expected_file "${CMAKE_MATCH_2}")
    file(SHA256 "${FIXTURE_DIR}/${expected_file}" actual_hash)
    if(NOT actual_hash STREQUAL expected_hash)
        message(FATAL_ERROR "Audio fixture hash mismatch: ${expected_file}")
    endif()
endforeach()
